"""Drift check for the managed `sync` artifacts (AGENTS.md section + .gitignore).

`super-harness sync --check` is a dry-run: it renders what `sync` WOULD write into
a throwaway temp copy of each managed artifact — reusing the EXACT init/sync render
path, so there is no second template — diffs that canonical result against the
on-disk file, and reports drift WITHOUT writing. Exit semantics live in the CLI.

API stability: **experimental** (v0.1).
"""
from __future__ import annotations

import difflib
import shutil
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from super_harness.engineering.agents_md_render import render_super_harness_section

# Bound a runaway diff (mirrors core/doc_check's _DIFF_MAX_LINES).
_DIFF_MAX_LINES = 40


@dataclass(frozen=True)
class ArtifactDrift:
    name: str   # "AGENTS.md" | ".gitignore"
    diff: str   # bounded unified diff (on-disk vs would-be-regenerated)


@dataclass
class SyncCheckResult:
    drift: list[ArtifactDrift] = field(default_factory=list)

    @property
    def in_sync(self) -> bool:
        return not self.drift


def _normalize(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def _read(path: Path) -> str:
    """Normalized text of ``path``; "" if absent / unreadable / non-UTF-8."""
    try:
        return _normalize(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError):
        return ""


def _bounded_diff(on_disk: str, canonical: str, name: str) -> str:
    diff = "".join(
        difflib.unified_diff(
            on_disk.splitlines(keepends=True),
            canonical.splitlines(keepends=True),
            fromfile=name,
            tofile=f"{name} (would be regenerated by `sync`)",
        )
    )
    lines = diff.splitlines(keepends=True)
    if len(lines) <= _DIFF_MAX_LINES:
        return diff
    extra = len(lines) - _DIFF_MAX_LINES
    return "".join(lines[:_DIFF_MAX_LINES]) + f"... ({extra} more lines)\n"


def _check_agents_md(root: Path, version: str, tmp: Path) -> ArtifactDrift | None:
    """Render the canonical AGENTS.md into a temp copy and diff vs on-disk."""
    agents = root / "AGENTS.md"
    tmp_agents = tmp / "AGENTS.md"
    if agents.exists():
        shutil.copyfile(agents, tmp_agents)
    # Reads adapters from the REAL root; writes the canonical section into the copy.
    render_super_harness_section(root, tmp_agents, version)
    canonical = _read(tmp_agents)
    on_disk = _read(agents)
    if canonical == on_disk:
        return None
    return ArtifactDrift(name="AGENTS.md", diff=_bounded_diff(on_disk, canonical, "AGENTS.md"))


def run_sync_check(
    root: Path,
    version: str,
    *,
    check_agents: bool,
    check_gitignore: bool,
) -> SyncCheckResult:
    """Render in-scope managed artifacts into a temp dir and report drift.

    ``check_agents`` / ``check_gitignore`` select which managed artifacts to
    inspect (the CLI maps the ``--agents-md`` / ``--gitignore`` scope flags). No
    file under ``root`` is ever written.
    """
    result = SyncCheckResult()
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        if check_agents:
            drift = _check_agents_md(root, version, tmp)
            if drift is not None:
                result.drift.append(drift)
        # .gitignore leg added in Task 3.
    return result
