"""AnchorIndexRebuilder sensor — rebuilds `.harness/anchors/index.yaml` on `merged`.

Phase 11 Task 11.2 (sensor-gate-architecture §3.1.10 — I-1 fix).

Design:
- Triggers on `merged` event.
- Calls scan_sentinel_locations to find every @capability:<id> with file+line.
- Writes (or overwrites) .harness/anchors/index.yaml mapping each anchor ID
  to a sorted list of {file, line} dicts.
- Silent: no events are emitted (purely computational, no state change events).

The standalone `rebuild_anchor_index(root)` function is also exported so the
`anchor sync` CLI (Task 11.3) can call it directly without fabricating an Event.

API stability: **experimental** (v0.1).
"""
from __future__ import annotations

from pathlib import Path
from typing import ClassVar

import yaml

from super_harness.core.anchor_scanner import scan_sentinel_locations
from super_harness.core.clock import utc_now_iso
from super_harness.core.events import Event
from super_harness.core.paths import anchors_index_path
from super_harness.sensors import Activity, Determinism, Sensor, SensorResult, WorkspaceContext


def rebuild_anchor_index(root: Path) -> SensorResult:
    """Scan root for @capability sentinels and write anchors/index.yaml.

    Idempotent: running twice produces the same file (modulo last_rebuilt_at).
    Returns a SensorResult with status='pass' and no emitted events.
    """
    locations = scan_sentinel_locations(root)
    anchors = {
        aid: [{"file": f, "line": ln} for f, ln in sorted(locs)]
        for aid, locs in sorted(locations.items())
    }
    out = anchors_index_path(root)
    out.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump({"last_rebuilt_at": utc_now_iso(), "anchors": anchors}, sort_keys=True)
    out.write_text("# AUTO-GENERATED by anchor-index-rebuilder. DO NOT EDIT.\n" + body)
    return SensorResult(
        status="pass",
        summary=f"rebuilt anchors/index.yaml with {len(anchors)} anchors",
    )


class AnchorIndexRebuilder(Sensor):
    """Rebuilds the anchor location index on every `merged` event.

    Writes `.harness/anchors/index.yaml` mapping each ``@capability:<id>``
    to the files and line numbers where it appears. Silent — no events emitted.

    See sensor-gate-architecture spec §3.1.10 (I-1 fix).
    """

    name: ClassVar[str] = "anchor-index-rebuilder"
    version: ClassVar[str] = "0.1.0"
    triggers_on_events: ClassVar[tuple[str, ...]] = ("merged",)
    determinism: ClassVar[Determinism] = "computational"

    def check(self, trigger: Event | Activity, context: WorkspaceContext) -> SensorResult:
        """Rebuild anchors/index.yaml from current source state.

        Silent: no events are emitted regardless of outcome.
        """
        return rebuild_anchor_index(context.workspace_root)
