"""Unit tests for AnchorIndexRebuilder sensor and rebuild_anchor_index helper (Phase 11 Task 11.2).

Cases:
1. rebuild writes anchors/index.yaml with correct {file, line} rows
2. AUTO-GENERATED header comment is present
3. sensor .check() returns status="pass" and emit_events == []
"""
from __future__ import annotations

from pathlib import Path

import yaml

from super_harness.core.events import Actor, Event
from super_harness.core.paths import anchors_index_path
from super_harness.sensors import WorkspaceContext
from super_harness.sensors.anchor_index_rebuilder import AnchorIndexRebuilder, rebuild_anchor_index


def _make_workspace(tmp_path: Path) -> Path:
    """Populate a minimal workspace with two source files containing sentinels."""
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "foo.py").write_text("# @capability:cap-foo\nprint('hi')\n")
    (tmp_path / "src" / "bar.ts").write_text("\n// @capability:cap-bar\nexport {};\n")
    return tmp_path


def test_rebuild_writes_correct_file_line_rows(tmp_path: Path) -> None:
    """rebuild_anchor_index writes anchors_index_path with {file, line} rows."""
    _make_workspace(tmp_path)
    rebuild_anchor_index(tmp_path)
    idx = yaml.safe_load(anchors_index_path(tmp_path).read_text())
    assert idx["anchors"]["cap-foo"][0] == {"file": "src/foo.py", "line": 1}
    assert idx["anchors"]["cap-bar"][0] == {"file": "src/bar.ts", "line": 2}


def test_rebuild_writes_autogenerated_header(tmp_path: Path) -> None:
    """Output file begins with the AUTO-GENERATED comment line."""
    _make_workspace(tmp_path)
    rebuild_anchor_index(tmp_path)
    text = anchors_index_path(tmp_path).read_text()
    assert text.startswith("# AUTO-GENERATED by anchor-index-rebuilder. DO NOT EDIT.")


def test_sensor_check_returns_pass_no_events(tmp_path: Path) -> None:
    """AnchorIndexRebuilder.check() returns status='pass' and emits no events."""
    _make_workspace(tmp_path)
    trigger = Event(
        event_id="e1",
        type="merged",
        change_id="c1",
        timestamp="2026-05-29T00:00:00Z",
        actor=Actor(type="sensor", identifier="test"),
        framework="plain",
    )
    result = AnchorIndexRebuilder().check(trigger, WorkspaceContext(workspace_root=tmp_path))
    assert result.status == "pass"
    assert result.emit_events == []
