"""Generate docs/state-machine.md by CALLING the live state machine.

Derives the reachability table from super_harness.core.transitions — it does
NOT transcribe the imperative branches, so the doc cannot drift from the code.
Emit to stdout: `python -m scripts.gen_state_machine --emit`. The gate
(`super-harness doc check`) owns regen-and-diff; this script just emits.
"""
from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass

from super_harness.core.events import KNOWN_EVENT_TYPES
from super_harness.core.state import STATES, TERMINAL_STATES
from super_harness.core.transitions import INVALID, compute_target_state

_HEADER = (
    "<!-- AUTOGENERATED by scripts/gen_state_machine.py — do not edit by hand. "
    "Regenerate with: super-harness doc check --fix -->"
)


@dataclass(frozen=True)
class Row:
    frm: str | None
    event: str
    to: str


def build_rows() -> list[Row]:
    rows: list[Row] = []
    sources: list[str | None] = [None, *STATES]
    for frm in sources:
        for event in sorted(KNOWN_EVENT_TYPES):
            to = compute_target_state(frm, event)
            if to == INVALID:
                continue
            if to == frm:           # self-loop (informational / re-emit) → not a move
                continue
            rows.append(Row(frm=frm, event=event, to=to))
    rows.sort(key=lambda r: ("" if r.frm is None else r.frm, r.event))
    return rows


def _noop_events() -> list[str]:
    """Events legal on every non-terminal state that leave it unchanged.

    Derived by CALLING the machine (not importing the private _INFORMATIONAL set).
    Excludes intent_declared (returns current on active states but is NOT
    informational); checks only non-terminal states (terminal states return
    INVALID for these events, which must not disqualify them).
    """
    nonterm = [s for s in STATES if s not in TERMINAL_STATES]
    out = []
    for event in sorted(KNOWN_EVENT_TYPES):
        if event == "intent_declared":
            continue
        if all(compute_target_state(s, event) == s for s in nonterm):
            out.append(event)
    return out


NOOP_EVENTS = _noop_events()


def render_markdown() -> str:
    lines = [_HEADER, "", "# Lifecycle state machine", "",
             "Generated from `super_harness.core.transitions`. Each row is a legal "
             "`(from, event) -> to` transition; `(start)` is the pre-first-event state.",
             "", "| from | event | to |", "|------|-------|----|"]
    for r in build_rows():
        frm = "(start)" if r.frm is None else r.frm
        lines.append(f"| `{frm}` | `{r.event}` | `{r.to}` |")
    lines += ["", "## Events that never change state", "",
              "These events are legal but leave the state unchanged "
              "(informational sensor signals):", ""]
    lines += [f"- `{e}`" for e in NOOP_EVENTS]
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="gen_state_machine")
    p.add_argument("--emit", action="store_true", required=True, help="Print the doc to stdout.")
    p.parse_args(argv)
    sys.stdout.write(render_markdown())
    return 0


if __name__ == "__main__":
    sys.exit(main())
